### ISSUE TITLE
Implement db querys for other fields

### ISSUE THREAD

**Issue by MathiasMehl** [cogitantium/jvm-loss#2]
As of right now, it is only possible to do querys based on timestamp, and not on drink type or event. Would be nice to be able to get all "coffee" or "Hot water" events

**Comment by falkecarlsen** [comment]
Event would probably always be `DispensedDrinkEvent`

**Comment by falkecarlsen** [comment]
I realised that that might not be right. We could be looking for different events at different times, e.g. `IngredientLevel` etc. I'm working on it :+1:

**Comment by falkecarlsen** [comment]
Resolved in #6
